version: '3.7'
services:
  homebridge:
    image: jonbackhaus/homebridge:test
    container_name: homebridge
    environment:
      - TZ=America/New_York
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    networks:
      - homebridge

  netshoot:
    image: nicolaka/netshoot:latest
    tty: true
    container_name: netshoot
    networks:
      - homebridge
    depends_on:
      - homebridge


networks:
  homebridge:
    driver: bridge
    name: homebridge
