version: 2.1
executors:
  executor-docker:
    environment:
      ORG_NAME: jonbackhaus
      IMAGE_NAME: homebridge
    docker:
      - image: cimg/base:2020.01
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN


jobs:
  job-build-image:
    executor: executor-docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build image
          command: |
            # echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            export IMAGE_URI=$ORG_NAME/$IMAGE_NAME
            docker build -t $IMAGE_URI -f Dockerfile .
            COMMIT_SLUG=${CIRCLE_SHA1:0:7}; echo "COMMIT_SLUG=$COMMIT_SLUG"
            docker tag $IMAGE_URI $IMAGE_URI:latest
            docker tag $IMAGE_URI $IMAGE_URI:$COMMIT_SLUG
            docker tag $IMAGE_URI $IMAGE_URI:$CIRCLE_BRANCH
            docker push $IMAGE_URI:latest
            docker push $IMAGE_URI:$COMMIT_SLUG
            docker push $IMAGE_URI:$IMAGE_DATE
            docker push $IMAGE_URI:$CIRCLE_BRANCH


workflows:
  version: 2
  workflow-any:
    jobs:
      - job-build-image